name: Auto Upload

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip wheel setuptools
          pip install aiohttp

      - name: Update
        env:
          SERVER: ${{ secrets.SERVER }}
          KEY: ${{ secrets.KEY }}
        run: |
          source venv/bin/activate
          python .github/scripts/generate_version.py
          python .github/scripts/summary.py
          python .github/scripts/upload.py

      - name: Commit Change
        run: |
          source venv/bin/activate
          python .github/scripts/commit.py
          git push
